version: '3'

# Networks
networks:
  # Internal network
  internal:
    driver: bridge

# Services
services:

  # Nginx
  app:
    image: webdevops/php-nginx-dev:8.0
    container_name: app
    networks:
      - internal
    volumes:
      - .:/var/www/app
      - .docker/app/usr/local/etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - PHP_DATE_TIMEZONE=UTC
      - PHP_DISPLAY_ERRORS=0
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MEMORY_LIMIT=4096M
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - PHP_DEBUGGER="xdebug"
      # - PHP_IDE_CONFIG="serverName=_"
      # xdebug v3
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_REMOTE_PORT=9090
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9090
      - XDEBUG_OUTPUT_DIR=/var/www/app/.xdebug
    expose:
      - 9090
    ports:
      - 8080:80
